### ISSUE TITLE
Not discoverable via MATLAB File Exchange

### ISSUE THREAD

**Issue by IndefiniteBen** [EwingKang/Dubins-Curve-For-MATLAB#2]
Thank you for your work on this, however it could be easier to find! Searching for Dubins curve on MathWorks/File Exchange currently returns only [Dubins Curve Mex](https://nl.mathworks.com/matlabcentral/fileexchange/40655-dubins-curve-mex) which also is based on AndrewWalker's work but far more outdated, not implemented in actual MATLAB functions and (obviously) unnecessarily done via mex. 
What you've done here is a much more MATLAB-friendly approach and more people should see, especially instead of the mex function. Can you please add this repo to file exchange? See: [About File Exchange - Linking with GitHub Repositories](https://nl.mathworks.com/matlabcentral/about/fx/#Why_GitHub) 
Then it will even be easy to add this from within MATLAB.

**Comment by EwingKang** [comment]
Hello IndefiniteBen. I didn't know a thing about File Exchange lol. I'll look into once I have a chance. I'm currently away from my computer. Thank you for the information.

**Comment by EwingKang** [comment]
Done, it's now on File Exchange
